name: amd64 BSD

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Only macos-12 runner provide virtualisation with vagrant/virtualbox installed.
# ref: https://github.com/actions/runner-images/tree/main/images/macos
jobs:
  vagrant:
    strategy:
      fail-fast: false
      matrix:
        distro: [freebsd,netbsd,openbsd]
    name: amd64•${{matrix.distro}}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: vagrant version
        run: Vagrant --version
      - name: VirtualBox version
        run: virtualbox -h
      - name: Build
        run: make --directory=ci ${{matrix.distro}}_build
